### PR TITLE
Update config.yml

### PR DESCRIPTION
**Pull request by mustard-studios**
added theme and owner

### CODE REVIEW

**Comment by mustard-studios** [comment]
Approved

**Review by mustard-studios — COMMENTED** [review]
yep

**Review by mustard-studios — COMMENTED** [review]
hghggg

**Review by mustard-studios — COMMENTED** [review]
why you no commit

**Review by mustard-studios — COMMENTED** [review]
fucking fine

**Comment by MustardBT** [comment]
Okay approved

**Review by mustard-studios — COMMENTED** [review]
Yep

**Pull request merged**
